### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by flying-sheep** [tk0miya/docutils-stubs#32]
Without a license, this cannot be used (no license has to be understood as “I have no rights to use this thing”)

Here’s a nice page helping with choosing one: https://choosealicense.com/

**Comment by tk0miya** [comment]
Indeed. I think this is a derivative of docutils. So it is better to derive its license to this package to me.
@cocoatomo What do you think?

**Comment by cocoatomo** [comment]
I basically agree with @tk0miya.

Then, we need to consider which license is applied to type annotations since docutils is covered by several licenses.
ref. [COPYING.txt](https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/COPYING.txt)

I prefer Public Domain because it is applied to much of source code of docutils. How about this?

**Comment by hyandell** [comment]
Encouraging a decision to be made :)

**Comment by zoofood** [comment]
Thanks for this package and the efforts to create it! 
I would love to use this, but I cannot without a license. Any chance it can be added?

**Comment by tk0miya** [comment]
Sorry, I've completely forgotten this issue. Okay, let's go with public domain. Can anyone send a PR? I'll merge it soon.
